### ISSUE TITLE
steno replay failed when nothing is listening at appUrl?

### ISSUE THREAD

**Issue by xingyu-he** [slackapi/steno#71]
### Description

I am using steno to write automation test, refer to https://github.com/slackapi/template-actionable-notifications
however, I failed and tips: connect ECONNREFUSED 127.0.0.1:5000 (app is listening at 5000)

Does it necessary to start app listening before launch steno?
While refer to example from slackapi/template-actionable-notifications, it's also launch steno first
> concurrently --kill-others --names steno,jest --success first "node test/launch-steno.js" "jest test/test.js"

[steno] already lauch steno
[steno] Listening for outgoing requests on port 3000
[steno] Incoming requests sent to: http://localhost:5000/
[steno] Control API started on port 4000
[steno] Controller started with scenario: untitled_scenario
[steno] events.js:183
[steno]       throw er; // Unhandled 'error' event
[steno]       ^
[steno] 
[steno] Error: connect ECONNREFUSED 127.0.0.1:5000
[steno]     at Object._errnoException (util.js:1024:11)
[steno]     at _exceptionWithHostPort (util.js:1046:20)
[steno]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[steno] node test/launch-steno.js exited with code 0
--> Sending SIGTERM to other processes..
[jest] jest test/test.js exited with code null

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/steno/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

steno version: V1.2.0

#### Steps to reproduce:
1. test/test.js 
/**
 * @jest-environment node
 */
describe('Test command', () => {
    beforeAll(async ()=>{
        await app.start();
    })
    test('test command', async () => {    
        // start steno
        await axios.post(`http://localhost:4000/start`, {
            name: 'command-test'
        }).then(()=>{
            const data = '**************'
            const options = {
            method: 'POST',
            headers: { 'content-type': 'application/x-www-form-urlencoded' },
            data: qs.stringify(data),
            url:'http://localhost:5000/command'
            };
            axios.post(options)
            return new Promise((r) => setTimeout(r, 1000));
        }).then(()=>{
            axios.post(`http://localhost:4000/stop`)
        }).then((history)=>{
            console.log(history)
        })
    });
    afterAll(async ()=>{
        console.log('afterEach');
        await app.stop();
    })
})
2.test/launch-steno.js
require('dotenv').config();
const path = require('path');
const cp = require('child_process');

const mode = process.argv[2] ? process.argv[2] : 'replay';

cp.spawn(`steno ${mode} http://localhost:${process.env.PORT}`, {
  shell: true,
  stdio: 'inherit',
});
// --app localhost:5000 --out-port 3000 --in-port 3010
console.log('already lauch steno');

3. package.json
"scripts": {
    "test:integration": "concurrently --kill-others --names steno,jest --success first \"node test/launch-steno.js\" \"jest test/test.js\""
  },

**Comment by xingyu-he** [comment]
Maybe it is framework problem, I change to mocha, launch steno success
